application: stockbroad
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: ticket.application

libraries:
- name: django
  version: "1.2"

builtins:
- remote_api: on
